server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/shop?currentSchema=shop
    username: admin
    password: admin
    driverClassName: org.postgresql.Driver
  liquibase:
    change-log: liquibase/changelog.yaml
#    default-schema: shop
#    liquibase-schema: shop
db:
  name: shop
  backup.path: /dump
logging:
  config: classpath:logback.xml
  level:
    org.springframework.jdbc.core:
      JdbcTemplate: DEBUG
      StatementCreatorUtils: TRACE
